# Generated by Django 4.2.3 on 2024-08-16 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0002_alter_goods_links'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goods',
            name='links',
            field=models.JSONField(blank=True, null=True, verbose_name='Ссылки'),
        ),
    ]
