# Generated by Django 4.2.3 on 2024-09-26 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0003_alter_goods_links'),
    ]

    operations = [
        migrations.CreateModel(
            name='Promo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now_add=True, verbose_name='Изменено')),
                ('name', models.CharField(db_index=True, max_length=255, verbose_name='Название')),
                ('code', models.CharField(db_index=True, max_length=255, verbose_name='Код')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('links', models.URLField(blank=True, null=True, verbose_name='Ссылка')),
                ('cost', models.PositiveIntegerField(blank=True, null=True, verbose_name='Стоимость')),
            ],
            options={
                'verbose_name': 'Промо',
                'verbose_name_plural': 'Промо',
                'ordering': ['id'],
            },
        ),
    ]
