# Generated by Django 4.2.3 on 2024-10-17 13:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('goods', '0004_promo'),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchasedPromo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchased_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата покупки')),
                ('promo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goods.promo', verbose_name='Промо')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Купленное промо',
                'verbose_name_plural': 'Купленные промо',
                'ordering': ['-purchased_at'],
                'unique_together': {('user', 'promo')},
            },
        ),
    ]
