# Generated by Django 4.2.3 on 2024-07-15 15:25

import base.fields
from django.conf import settings
from django.db import migrations
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_alter_user_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='point',
            name='user',
            field=base.fields.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='points', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='referral',
            name='user',
            field=base.fields.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referrals', to=settings.AUTH_USER_MODEL, verbose_name='Создатель кода'),
        ),
    ]
