# Generated by Django 4.2.3 on 2024-09-14 08:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_tempcode_user_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='point',
            name='created_at',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, verbose_name='Создано'),
        ),
        migrations.AddField(
            model_name='point',
            name='text',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Текст'),
        ),
    ]
