# Generated by Django 4.2.3 on 2024-09-27 19:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_point_charge'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_admin',
        ),
        migrations.RemoveField(
            model_name='user',
            name='jwt_updated_at',
        ),
        migrations.RemoveField(
            model_name='user',
            name='permissions',
        ),
        migrations.RemoveField(
            model_name='user',
            name='roles',
        ),
        migrations.DeleteModel(
            name='Permission',
        ),
    ]
