# Generated by Django 4.2.3 on 2024-10-13 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='message_eng',
            field=models.TextField(blank=True, null=True, verbose_name='Сообщение на ENG'),
        ),
        migrations.AddField(
            model_name='notification',
            name='topik_eng',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Заголовок на ENG'),
        ),
    ]
