# Generated by Django 4.2.3 on 2024-10-13 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_notification_message_eng_notification_topik_eng'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notification',
            options={'ordering': ['-created_at'], 'verbose_name': 'Уведомление', 'verbose_name_plural': 'Уведомления'},
        ),
    ]
