# Generated by Django 4.1.3 on 2024-11-23 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0012_alter_notification_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='tempcode',
            name='verified',
            field=models.BooleanField(default=False, verbose_name='Подтвержден?'),
        ),
    ]
