# Generated by Django 4.2.3 on 2024-07-11 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ads',
            name='images',
            field=models.FileField(upload_to='ads/', verbose_name='Изображение'),
        ),
    ]
