# Generated by Django 4.2.3 on 2024-10-13 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_mailing'),
    ]

    operations = [
        migrations.AddField(
            model_name='mailing',
            name='description_eng',
            field=models.TextField(default='', verbose_name='Описание на ENG'),
        ),
        migrations.AddField(
            model_name='mailing',
            name='title_eng',
            field=models.CharField(default='', max_length=255, verbose_name='Заголовок на ENG'),
        ),
    ]
