# Generated by Django 4.2.3 on 2024-07-15 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0003_favoriterecipe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='ingredients',
            field=models.ManyToManyField(blank=True, related_name='recipes_ingr', to='recipe.ingredient', verbose_name='Ингредиенты'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='tools',
            field=models.ManyToManyField(blank=True, related_name='recipes_tool', to='recipe.tool', verbose_name='Инструменты'),
        ),
    ]
