# Generated by Django 4.2.3 on 2024-07-26 13:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0004_alter_recipe_ingredients_alter_recipe_tools'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='ingredients',
        ),
        migrations.AlterField(
            model_name='recipe',
            name='instruction',
            field=models.JSONField(blank=True, null=True, verbose_name='Инструкция'),
        ),
        migrations.CreateModel(
            name='RecipeIngredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Количество')),
                ('type', models.CharField(choices=[('ml', 'мл'), ('l', 'л'), ('tsp', 'ч. л.'), ('tbsp', 'ст. л.'), ('cup', 'ст.'), ('pt', 'пинта'), ('qt', 'кварта'), ('gal', 'галлон'), ('fl oz', 'унция жидкостная'), ('mg', 'мг'), ('g', 'г'), ('kg', 'кг'), ('t', 'т'), ('oz', 'унция'), ('lb', 'фунт')], default='ml', max_length=10, verbose_name='Мера')),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredient_recipes', to='recipe.ingredient')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipe_ingredients', to='recipe.recipe')),
            ],
            options={
                'verbose_name': 'Ингредиент рецепта',
                'verbose_name_plural': 'Ингредиенты рецепта',
                'unique_together': {('recipe', 'ingredient')},
            },
        ),
    ]
