# Generated by Django 4.2.3 on 2024-09-19 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0008_remove_ingredient_description_eng_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredientcategory',
            name='is_alcoholic',
            field=models.BooleanField(default=False, verbose_name='Алкогольный?'),
        ),
        migrations.AddField(
            model_name='ingredientcategory',
            name='is_main',
            field=models.BooleanField(default=False, verbose_name='Основная?'),
        ),
    ]
