# Generated by Django 4.2.3 on 2024-09-22 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0009_ingredientcategory_is_alcoholic_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='IngredientCategorySection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now_add=True, verbose_name='Изменено')),
                ('name', models.CharField(max_length=255, verbose_name='Название блока категорий')),
                ('categories', models.ManyToManyField(related_name='category_blocks', to='recipe.ingredientcategory', verbose_name='Категории')),
            ],
            options={
                'verbose_name': 'Блок категорий',
                'verbose_name_plural': 'Блоки категорий',
            },
        ),
    ]
