# Generated by Django 4.2.3 on 2024-09-22 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0010_ingredientcategorysection'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredientcategorysection',
            name='language',
            field=models.CharField(choices=[('ENG', 'Английский'), ('RUS', 'Русский')], default='RUS', max_length=20, verbose_name='Язык'),
        ),
    ]
