# Generated by Django 4.2.3 on 2024-07-11 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TinkoffPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('tries', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Количество попыток')),
                ('type', models.CharField(choices=[('plan', 'Генерация учебного плана')], default='plan', max_length=6, verbose_name='Тип')),
                ('status', models.CharField(choices=[('CREATED', 'Платеж зарегистрирован в шлюзе, но его обработка в процессинге не начата'), ('NEW', 'Инициализирован'), ('CANCELED', 'Отменен'), ('DEADLINE_EXPIRED', 'Время сессии истекло'), ('FORM_SHOWED', 'Покупатель переправлен на страницу оплаты'), ('AUTHORIZING', 'Аутентификация покупателя'), ('REJECTED', 'Отклонено банком'), ('3DS_CHECKING', 'Начало аутентификация 3-D Secure'), ('3DS_CHECKED', 'Завершение аутентификации 3-D Secure'), ('AUTH_FAIL', 'Не пройдена аутентификация 3-D Secure'), ('PAY_CHECKING', 'Платеж обрабатывается'), ('AUTHORIZED', 'Средства заблокированы, но не списаны'), ('REVERSING', 'Начало отмены блокировки средств'), ('REVERSED', 'Денежные средства разблокированы'), ('CONFIRMING', 'Начало списания денежных средств'), ('CONFIRM_CHECKING', 'Платеж обрабатывается'), ('CONFIRMED', 'Денежные средства списаны'), ('REFUNDING', 'Начало возврата денежных средств'), ('ASYNC_REFUNDING', 'Обработка возврата денежных средств по QR'), ('REFUNDED', 'Произведен возврат денежных средств'), ('PARTIAL_REFUNDED', 'Произведен частичный возврат денежных средств')], default='CREATED', max_length=17, verbose_name='Статус')),
                ('terminal_key', models.CharField(max_length=50, verbose_name='Идентификатор терминала')),
                ('description', models.CharField(max_length=140, verbose_name='Краткое описание')),
                ('tinkoff_id', models.CharField(blank=True, max_length=255, null=True, verbose_name='ID транзакции в системе банка')),
                ('payment_url', models.URLField(blank=True, null=True, verbose_name='Ссылка на платежную форму')),
                ('amount', models.PositiveIntegerField(verbose_name='Сумма в копейках')),
                ('token', models.CharField(max_length=64, verbose_name='Токен')),
                ('error_code', models.CharField(blank=True, max_length=10, null=True, verbose_name='Код ошибки')),
                ('message', models.TextField(blank=True, null=True, verbose_name='Описание ошибки')),
                ('success', models.BooleanField(blank=True, null=True, verbose_name='Выполнение платежа')),
                ('fee', models.PositiveIntegerField(default=0, verbose_name='Размер комиссии в копейках')),
            ],
            options={
                'verbose_name': 'Платеж через Tinkoff',
                'verbose_name_plural': 'Платежи через Tinkoff',
            },
        ),
    ]
